```{r}
library(DropletUtils)
library(SingleCellExperiment)
library(scater)
```

```{r}
mat <- Matrix::readMM('data/collab/LWScone/matrix.mtx')
barcodes <- read.delim('data/collab/LWScone/barcodes.tsv', header = FALSE)
genes <- read.delim('data/collab/LWScone/genes.tsv', header = FALSE)

rownames(mat) <- genes$V1
colnames(mat) <- barcodes$V1

# drop  EFGP RFP
mat <- mat[rownames(mat)!= "EGFP",]
mat <- mat[rownames(mat)!= "RFP",]
```

```{r}
sce <- SingleCellExperiment(assays = list(counts = mat))
```

```{r}
sce
```

```{r}
cellqc <- perCellQCMetrics(sce)
colData(sce) <- cellqc
```

```{r}
plotColData(sce, y = "sum") +
  scale_y_log10() +
  ggtitle("Total Counts")
```

```{r}
bcrank <- barcodeRanks(counts(sce))
uniq <- !duplicated(bcrank$rank)
plot(bcrank$rank[uniq], bcrank$total[uniq], log="xy",
    xlab="Rank", ylab="Total UMI count", cex.lab=1.2)

abline(h=metadata(bcrank)$inflection, col="darkgreen", lty=2)
abline(h=metadata(bcrank)$knee, col="dodgerblue", lty=2)

legend("bottomleft", legend=c("Inflection", "Knee"), 
        col=c("darkgreen", "dodgerblue"), lty=2, cex=1.2)
```

```{r}
bcrank
```

```{r}
library(scds)
sce <- cxds_bcds_hybrid(sce)
```

```{r}
sce$doublet_outlier <- isOutlier(sce$hybrid_score, nmads = 5)
hist(sce$hybrid_score) 
abline(v = min(sce$hybrid_score[sce$doublet_outlier]), col = "firebrick",
      lty = 2)
```

```{r}
table(sce$doublet_outlier)
```

```{r}
sce.filtered <- sce[,!sce$doublet_outlier]
table(sce.filtered$doublet_outlier)
```

```{r}
plotHighestExprs(sce.filtered[,sample(seq_len(ncol(sce.filtered)), 200)], exprs_values = "counts")
```
```{r}
?scater::numDetectedAcrossCells
```
```{r}
detected <- numDetectedAcrossFeatures(sce.filtered, ids = rownames(sce))
n_cells_per_gene <- rowSums(detected)
table(n_cells_per_gene > 0)
```



```{r}
counts_per_gene <- scater::nexprs(sce.filtered, byrow=TRUE, detection_limit = 1)
table(counts_per_gene > 5)
```
```{r}
sce.filtered <- sce.filtered[counts_per_gene >5, ]
```


```{r}
scater::plotRLE(sce.filtered[, order(sce.filtered$detected)], style = "minimal", colour_by = "detected",
                exprs_values = "counts"
                )
```
```{r}
logcounts(sce.filtered) <- log2(calculateCPM(sce.filtered) + 1)
scater::plotRLE(sce.filtered[, order(sce.filtered$detected)], style = "minimal", colour_by = "detected",
                exprs_values = "logcounts"
                )
```

